name: sos_admin
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  graphql_flutter: ^5.1.2
  encrypt: ^5.0.3
  flutter_image_compress: ^2.1.0
  shared_preferences: ^2.2.2
  jwt_decoder: ^2.0.1
  enum_to_string: ^2.0.1
  sizer: ^2.0.15
  font_awesome_flutter: ^10.6.0
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  url_launcher: ^6.2.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  build_runner:
  flutter_gen_runner:
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/


